import React, { useState } from "react";

function GetOptions({ onOptionChange }) {
  const [includeUppercase, setIncludeUppercase] = useState(true);
  const [includeLowercase, setIncludeLowercase] = useState(true);
  const [includeNumbers, setIncludeNumbers] = useState(true);
  const [includeSpecial, setIncludeSpecial] = useState(true);
  const [includeRepeating, setIncludeRepeating] = useState(false);
  const [passwordLength, setPasswordLength] = useState(14);

  return (
    <div>
      <div className="outer">
        <div className="inner2">
          <h2>
            Define how you want your password to be generated by selecting the
            options below.
          </h2>
        </div>

        <div className="inner1">
          <label>
            <input
              type="checkbox"
              checked={includeUppercase}
              onChange={(e) => setIncludeUppercase(e.target.checked)}
            />
            Include uppercase letters
          </label>
          <br />

          <label>
            <input
              type="checkbox"
              checked={includeLowercase}
              onChange={(e) => setIncludeLowercase(e.target.checked)}
            />
            Include lowercase letters
          </label>
          <br />

          <label>
            <input
              type="checkbox"
              checked={includeNumbers}
              onChange={(e) => setIncludeNumbers(e.target.checked)}
            />
            Include numbers
          </label>
          <br />

          <label>
            <input
              type="checkbox"
              checked={includeSpecial}
              onChange={(e) => setIncludeSpecial(e.target.checked)}
            />
            Include special characters
          </label>
          <br />

          <label>
            <input
              type="checkbox"
              checked={includeRepeating}
              onChange={(e) => setIncludeRepeating(e.target.checked)}
            />
            Allow repeating characters
          </label>
          <br />

          <label>
            Number of characters:
            <br />
          </label>
          <input
            type="number"
            value={passwordLength}
            onChange={(e) => setPasswordLength(Number(e.target.value))}
          />
        </div>

        <div className="inner2">
          <button
            onClick={() => {
              let optionsArray = [
                includeUppercase,
                includeLowercase,
                includeNumbers,
                includeSpecial,
                includeRepeating,
                passwordLength,
              ];
              onOptionChange(optionsArray);
            }}
          >
            Generate Password
          </button>
        </div>
      </div>
    </div>
  );
}
export default GetOptions;
